version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: ipdb
    versions:
    - 0.13.5
    - 0.13.6
  - dependency-name: pygments
    versions:
    - 2.8.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: libcst
    versions:
    - 0.3.17
  - dependency-name: mypy
    versions:
    - "0.800"
